### ISSUE TITLE
Issue in "qsub extract_reads_from_kmers.sh kmer.file.sorted.kmer"

### ISSUE THREAD

**Issue by MEnders83** [cprodhom/CoSSA-workflows#1]
When starting the "extract_reads_from_kmers.sh" script we encountered the following error message (in german): 
Speicherzugriffsfehler (Speicherabzug geschrieben)

From my first search, this seem to be a C++ exception. I´m not perfectly sure, but most probably this is a segmentation fault.

As our dataset is privat, please contact me for details.

Thanks!

**Comment by AurelieE79** [comment]
Hi, 
 yes it seems the problem is not fixable for an external source as this is a compilation issue from the C++ program named "kfastqfilter". 
could it be possible to add the source code of "kfastqfilter" ? or send it privately ?
regards and thanks !

**Comment by danessel** [comment]
we are updating the CoSSA pipeline using more efficient tools like KMC3. KMC_tools has a module to extract reads based on the kmers.
Maybe this helps for now

**Comment by bejo-dionnez** [comment]
Hi @danessel, 

Is there any news on the update of the CoSSa pipeline? 

We are currently also running into the issue mentioned above but are trying to replace the extract_from_reads.sh script with kmc_tools filter.

Regards, Dionne

**Comment by danessel** [comment]
Ha Dionne,

Thanks for your interest and reminding me. Unfortunately it is still on the list of things todo.
